POST  http://localhost:8080/films 
Content-Type: application/json

{
    "name":"Шазам!",
    "description":"Четырнадцатилетний Билли Бэтсон не предполагал, что всего одно слово, причём, по его мнению, звучащее глупо, способно изменить жизнь... Для парнишки этим словом стало «Шазам!». Билли, потерявший родителей, сбежал из шести приёмных семей. Подросток уверен, что он способен позаботиться о себе самостоятельно, однако, директор приюта отправила юношу к очередным родителям. Новое окружение оказалось тёплым и дружелюбным. Бэтсон познакомился со своим «братом» — Фредди Фриманом, тоже усыновлённым мальчиком. Фредди одержим ...",
    "poster":"http://kinogo.eu/uploads/posts/2019-02/1549544600_shazam.jpg"
}

###
GET http://localhost:8080/films/1
Content-Type: application/json

###
GET http://localhost:8080/movies
Content-Type: application/json

###
DELETE http://localhost:8080/movies/5cb4a7b3a2ff2d06545ed527
Content-Type: application/json

###
GET http://localhost:8080
Content-Type: application/json

###
PUT http://localhost:8080/movies/5cb4a666a2ff2d06545ed523
Content-Type: application/json

{
    "name":"Время монстров",
    "description":"Авторы фантастического кинофильма «Время монстров» погружают зрителей в мрачную и жуткую эпоху Средневековья. На экране на протяжение всего фильма вы не увидите ярких красок и не услышите красивой музыки и смеха. Только черные искорёженные деревья, грязные развалины и нечеловеческий дикий крик героя хоррора. Когда-то очень давно его единственную дочурку растерзали чудовищные ненасытные твари, и уже много лет убитый горем отец хочет найти и уничтожить виновных в смерти девочки.",
    "poster":"http://kinogo.eu/uploads/posts/2019-04/1554984843_vremya-monstrov.jpg"
}

###
POST  http://localhost:8080/cinemas 
Content-Type: application/json

{
    "name":"Zvezda",
    "halls": [{
        "name":"hall 1",
        "places": [
            {
            "row": 1,
            "countOfSeats": 20,
            "cost": 10
            },
            {
            "row": 2,
            "countOfSeats": 24,
            "cost": 20
            },
            {
            "row": 3,
            "countOfSeats": 24,
            "cost": 30
            },
            {
            "row": 4,
            "countOfSeats": 24,
            "cost": 40
            },
             {
            "row": 5,
            "countOfSeats": 24,
            "cost": 50
            },
            {
            "row": 6,
            "countOfSeats": 24,
            "cost": 60
            },
            {
            "row": 7,
            "countOfSeats": 24,
            "cost": 70
            }
        ]
    }]
}

###
GET http://localhost:8080/cinemas
Content-Type: application/json

###
GET http://localhost:8080/cinemas/5cb487124f307f0da0038521?select=halls
Content-Type: application/json

###
GET http://localhost:8080/cinemas/5cb487124f307f0da0038521/1
Content-Type: application/json

###
POST  http://localhost:8080/sessions 
Content-Type: application/json

{
    "date" : 1555488000000,
    "cinema" : "5cb4a2b7a2ff2d06545ed51f",
    "hall":"hall green",
    "movie" : "5cb727ed3f59f42ff8b91873",
    "selectedSeats": [
    ]
}

###
GET  http://localhost:8080/sessions 
Content-Type: application/json

###
GET  http://localhost:8080/sessions/5cb727ed3f59f42ff8b91873 
Content-Type: application/json

###
GET  http://localhost:8080/seanses/5c98e28f824ad91ba4d67f10?select=selectedSeats
Content-Type: application/json

###
PUT  http://localhost:8080/sessions/insert/5cee3f8d4ec32366e096f3da 
Content-Type: application/json

{
    "row": 1,
    "seat": 9,
    "price": 100
}

###
PUT  http://localhost:8080/session/delete/5ceda031af32426df4698757  
Content-Type: application/json

{
    "row": 10,
    "seat": 9,
    "price": 1000
}

###
PUT http://localhost:8080/cinemas/insert/5cb487124f307f0da0038521
Content-Type: application/json

{
    "name":"golden",
        "places": [
            {
            "row": 1,
            "countOfSeats": 10,
            "cost": 1000
            },
            {
            "row": 2,
            "countOfSeats": 12,
            "cost": 2000
            },
            {
            "row": 3,
            "countOfSeats": 12,
            "cost": 3000
            },
            {
            "row": 4,
            "countOfSeats": 12,
            "cost": 4000
            },
             {
            "row": 5,
            "countOfSeats": 12,
            "cost": 5000
            }
        ]
}

###
POST  http://localhost:8080/users 
Content-Type: application/json

{
    "name" : "Sergey",
    "login" : "qwerasss",
    "password" : "98123",
    "email" : "sdferty@mail.com"   
}

###
GET  http://localhost:8080/users 
Content-Type: application/json